### ISSUE TITLE
add config file for disable \ settings spawn mobs

### ISSUE THREAD

**Issue by TABURELTER** [bageldotjpg/BuzzierBees#168]
Please add to the mod a config to disable the spawning of mobs from the mod

**Comment by bageldotjpg** [comment]
Already doable via datapack

**Comment by TABURELTER** [comment]
> Already doable via datapack

Can you send me a link to the datapack?

**Comment by bageldotjpg** [comment]
The datapack hasn't been made, but this is doable via making your own datapack quite simply. If you'd like to disable Mooblooms spawning, you just empty out the [`buzzier_bees:has_animal/moobloom`](https://github.com/team-abnormals/buzzier-bees/blob/1.19.x/src/generated/resources/data/buzzier_bees/tags/worldgen/biome/has_animal/moobloom.json) tag.
