### ISSUE TITLE
Honeycomb banner pattern not visible on 1.19

### ISSUE THREAD

**Issue by mintynoura** [bageldotjpg/BuzzierBees#171]
I'm using forge 41.1.0, buzzier bees 5.0.0, and blueprint 6.0.5. This issue is also present in the chimpanzee banner pattern from neapolitan.

**Comment by bageldotjpg** [comment]
Can not reproduce. What do you mean not visible?

**Comment by mintynoura** [comment]
The banner stays blank no matter the color of dye i use. Actually, it might be a mod incompat with optifine or something. Sorry
