### ISSUE TITLE
Crashes with Outer End. (Or some Create incompat. issue)

### ISSUE THREAD

**Issue by MagmaSlime123** [bageldotjpg/BuzzierBees#176]
Title.

No report is made, I'm simply kicked to the multiplayer screen. This isn't a server, this is singleplayer.
Log file mentions issues with Outer End's Violite-related recipes not working correctly.

[latest.log](https://github.com/team-abnormals/buzzier-bees/files/9832347/latest.log)
Would've uploaded this to Pastebin, but it hates how big this file is and refuses to work with it.
GitHub Gists will just cut it off randomly.

**Comment by bageldotjpg** [comment]
Old issue by now and could be fixed but this log is rather impossible to look through and confirm really anything

**Comment by MagmaSlime123** [comment]
Noot sure why this took over a year to get an answer for. But again, Outer End's recipes are the culprit.
