### ISSUE TITLE
Mod Doesn't Work Fully on 1.19.2

### ISSUE THREAD

**Issue by CaptainRagequit** [bageldotjpg/BuzzierBees#179]
![Buzzier Bees Limited Items](https://user-images.githubusercontent.com/120533903/207480166-04f96322-5b92-42ff-9c0e-18af8c22f83b.png)
The Items we have available are very limited compared to how much the mod usually offers. We (My friends and I) are running on a private server, using a custom modpack we put together. We think the issue is that the most recent upload of the Buzzier Bees mod is for 1.19, but it says it's compatible with 1.19.2. It could be another issue, of course. Here is a link to our modpack to review if need be: https://www.curseforge.com/minecraft/modpacks/morose-try-sexual-pack

**Comment by CaptainRagequit** [comment]
If any questions come up, feel free to ask me, and My friends and I will try our best to answer!

**Comment by bageldotjpg** [comment]
A lot of items were removed - some because Mojang added stuff like candles, and some because they were features we were quite unhappy with. The things that were removed will be replaced with new content in due time.
