### ISSUE TITLE
[Question] Custom textured beehives will return on 1.18?

### ISSUE THREAD

**Issue by hron84** [bageldotjpg/BuzzierBees#180]
I love your custom beehives in 1.16 packs and I was very sad when I realized they are not a thing anymore under 1.18. 
Do you plan to bring them back? It would be really awesome!

**Comment by bageldotjpg** [comment]
Custom beehives have moved to our new mod, [Woodworks](https://www.curseforge.com/minecraft/mc-mods/woodworks).
If you are worried about overlap with other mods - worry not, because all the features are easy to disable in the config, so it is easy to just have the beehives.
